// src/main/resources/boot/angular-tutorial/start/src/app/components/todolist/todolist.component.ts
import { Component, OnInit } from '@angular/core';

import { SessionStorageService } from '../../services/session-storage.service';

@Component({
  selector: 'app-todolist',
  templateUrl: './todolist.component.html',
  styleUrls: ['./todolist.component.css']
})
export class TodolistComponent implements OnInit {

  private sessionKey: string = 'todo-list';

  private newTodoContent: string = '';
  private todoList: object[] = [];
  private finishedList: object[] = [];

  constructor(private session: SessionStorageService) {
    this.read();
  }

  ngOnInit() {

  }

  newTodoContentChange(e) {
    let { target, keyCode } = e;
    let { value } = target;
    if (!value) { return; }
    if (keyCode === 13) {
      this.addTodo(value);
    }
  }

  todoStatusChange(e, todo: object) {
    let { checked } = e.target;
    let { todoList, finishedList } = this;
    if (checked) {
      todoList.splice(todoList.findIndex(item => todo === item), 1);
      finishedList.push(todo);
    } else {
      finishedList.splice(finishedList.findIndex(item => todo === item), 1);
      todoList.push(todo);
    }
    this.save();
  }

  removeTodo(todo: object) {
    this.todoList.splice(this.todoList.findIndex(item => todo === item), 1);
    this.save();
  }

  addTodo(content: string) {
    let target = this.todoList.find((item: any) => content === item.content);
    if (target) {
      return alert('it exists!');
    }
    this.todoList.push({ content, status: false });
    this.save();
    this.newTodoContent = '';
  }

  save() {
    this.session.set(this.sessionKey, this.todoList.concat(this.finishedList));
  }

  read() {
    this.todoList.length = 0;
    this.finishedList.length = 0;

    let list: object[] = this.session.get(this.sessionKey);
    list && list.forEach((item: any) => {
      if (item.status) {
        this.finishedList.push(item);
      } else {
        this.todoList.push(item);
      }
    });
  }

}
<div class="todolist">
  <h2>To Do List</h2>
  <input class="new-todo-content" [(ngModel)]="newTodoContent" (keyup)="newTodoContentChange($event)"
    placeholder="please input, key enter add!" />
  <hr />
  TODO
  <ol>
    <li *ngFor="let item of todoList;let key=index;">
      <input type="checkbox" [id]="'todo_'+key" (change)="todoStatusChange($event,item)" [(ngModel)]="item.status" />
      <label [for]="'todo_'+key">{{item.content}}--</label>
      <button (click)="removeTodo(item)">remove</button>
    </li>
  </ol>
  <hr />
  FINISHED
  <ol>
    <li *ngFor="let item of finishedList;let key=index;">
      <input type="checkbox" [id]="'finish_todo_'+key" (change)="todoStatusChange($event,item)"
        [(ngModel)]="item.status" />
      <label [for]="'finish_todo_'+key">{{item.content}}</label>
    </li>
  </ol>
</div>

// src/main/resources/boot/react-turorial/start/src/components/TodoList.js
import React from 'react';

class TodoList extends React.Component {
    constructor(props) {
        super(props);

        this.keySeed = Date.now();

        this.state = {
            newTodo: '',
            list: []
        };
    }

    newKey() {
        return (++this.keySeed).toString(36);
    }

    enterAddTodo = (e) => {
        if (e.keyCode === 13) {
            this.addTodo();
        }
    }

    addTodo = () => {
        let newTodo = this.refs.newTodo;
        if (newTodo.value.length > 0) {
            let list = this.state.list;
            let title = newTodo.value;

            let target = list.find(item => title === item.title);
            if (target) {
                return alert('It already exists!');
            }

            let key = this.newKey();
            let checked = false;

            list.push({ key, title, checked });
            this.setState({ list });
            this.saveList();
            newTodo.value = '';
        }
    }

    changeTodoChecked = (key) => {
        let list = this.state.list;
        let target = list.find(item => key === item.key);
        if (target) {
            target.checked = !target.checked;
            this.setState({ list });
            this.saveList();
        }
    }

    removeTodo = (key) => {
        let list = this.state.list;
        let index = list.findIndex(item => key === item.key);
        if (index > -1) {
            list.splice(index, 1);
            this.setState({ list });
            this.saveList();
        }
    }

    saveList() {
        sessionStorage.setItem('list', JSON.stringify(this.state.list));
    }

    componentDidMount() {
        let list = sessionStorage.getItem('list');
        if (list) {
            try {
                list = JSON.parse(list);
                this.setState({ list });
            } catch (e) {
                console.log(e);
            }
        }
    }

    render() {
        let todoList = this.state.list.filter(item => !item.checked);
        let finishedList = this.state.list.filter(item => item.checked);

        return (
            <div>
                <h2>Welcome todoList!</h2>
                <div>
                    <input ref="newTodo" onKeyUp={this.enterAddTodo} />
                    <button onClick={this.addTodo}>Add new to do</button>
                </div>
                <div>
                    <h3>Todo</h3>
                    <ol>
                        {
                            todoList.map(item => {
                                return (
                                    <li key={item.key}>
                                        <input type="checkbox" checked={item.checked} onChange={this.changeTodoChecked.bind(this, item.key)} />
                                        {item.title}
                                        <button onClick={this.removeTodo.bind(this, item.key)}>remove</button>
                                    </li>
                                )
                            })
                        }
                    </ol>
                </div>
                <div>
                    <h3>Finished</h3>
                    <ol>
                        {
                            finishedList.map(item => {
                                return (
                                    <li key={item.key}>
                                        <input type="checkbox" checked={item.checked} onChange={this.changeTodoChecked.bind(this, item.key)} />
                                        {item.title}
                                    </li>
                                )
                            })
                        }
                    </ol>
                </div>
            </div>
        )
    }
}

export default TodoList;
